repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        types: [python]
      - id: end-of-file-fixer
        types: [python]
      - id: debug-statements
        types: [python]
      - id: mixed-line-ending
        args: [ '--fix=lf' ]
        description: Forces to replace line ending by the UNIX 'lf' character.
        types: [python]
      - id: check-merge-conflict
        types: [python]
      - id: check-ast
        types: [python]

  - repo: https://github.com/psf/black
    rev: '23.7.0'
    hooks:
    - id: black
      types: [python]
      args: [-l, '100']

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff
        args: ["--select=TID252", "--per-file-ignores=__init__.py:F401", "--per-file-ignores=__init__.py:TID252"]