# Generated by Django 4.0.3 on 2022-04-03 08:19

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("is_required", models.BooleanField(verbose_name="Обязательный")),
            ],
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("position", models.IntegerField(verbose_name="Позиция")),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=["name"], required_languages=(), virtual_fields=True
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institution.institution",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория продуктов",
                "verbose_name_plural": "Категории продуктов",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                ("image", models.ImageField(upload_to="product_images/", verbose_name="Картинка")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "активен"), ("inactive", "неактивен")],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
                ("price", models.IntegerField(verbose_name="Цена")),
                ("tags", models.TextField(verbose_name="Теги")),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="product.productcategory",
                        verbose_name="Категория",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institution.institution",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
        migrations.CreateModel(
            name="OptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("adding_price", models.IntegerField(verbose_name="Цена добавления")),
                ("is_default", models.BooleanField(verbose_name="По умолчанию")),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="product.productoption",
                    ),
                ),
            ],
        ),
    ]
