# Generated by Django 4.0.3 on 2022-04-03 11:10

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=["name", "description"], required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=["title"], required_languages=(), virtual_fields=True
            ),
        ),
    ]
