# Generated by Django 4.0.3 on 2022-04-03 15:36

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0002_product_i18n_productoption_i18n"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="institution",
        ),
        migrations.AddField(
            model_name="optionitem",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=["title"], required_languages=(), virtual_fields=True
            ),
        ),
    ]
