# Generated by Django 4.0.3 on 2022-04-03 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_remove_product_institution_optionitem_i18n"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="optionitem",
            options={
                "verbose_name": "Элемент дополнения",
                "verbose_name_plural": "Элементы дополнения",
            },
        ),
        migrations.AlterModelOptions(
            name="productoption",
            options={"verbose_name": "Дополнение", "verbose_name_plural": "Дополнения"},
        ),
        migrations.AddField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="product.product"
            ),
            preserve_default=False,
        ),
    ]
