# Generated by Django 4.0.3 on 2022-04-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0004_alter_optionitem_options_alter_productoption_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LikedInstitutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="liked_products",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="likes",
                        to="product.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("customer", "product")},
            },
        ),
    ]
