# Generated by Django 4.0.3 on 2022-04-08 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_likedinstitutions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="product.product",
            ),
        ),
    ]
