# Generated by Django 4.0.3 on 2022-04-08 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0004_alter_likedinstitutions_customer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0006_alter_productoption_product"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="LikedInstitutions",
            new_name="LikedProducts",
        ),
        migrations.AlterField(
            model_name="productcategory",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="category_set",
                to="institution.institution",
                verbose_name="Заведение",
            ),
        ),
    ]
