# Generated by Django 4.0.3 on 2022-04-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_rename_likedinstitutions_likedproducts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionitem",
            name="id_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
        migrations.AlterField(
            model_name="optionitem",
            name="option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="product.productoption",
            ),
        ),
    ]
