# Generated by Django 4.0.3 on 2022-04-12 10:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_optionitem_id_deleted_alter_optionitem_option"),
    ]

    operations = [
        migrations.RenameField(
            model_name="optionitem",
            old_name="id_deleted",
            new_name="is_deleted",
        ),
    ]
