# Generated by Django 4.0.3 on 2022-06-04 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_rename_id_deleted_optionitem_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
    ]
