# Generated by Django 4.0.4 on 2022-07-07 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0018_institution_secondary_categories_and_more"),
        ("product", "0010_remove_product_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategory",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_set",
                to="institution.institution",
                verbose_name="Заведение",
            ),
        ),
    ]
