# Generated by Django 4.0.4 on 2022-08-08 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0018_institution_secondary_categories_and_more"),
        ("product", "0012_alter_likedproducts_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="institution",
            field=models.ForeignKey(
                default=9,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
                verbose_name="Заведение",
            ),
            preserve_default=False,
        ),
    ]
