# Generated by Django 4.0.3 on 2022-10-31 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0014_productcategory_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="optionitem",
            name="is_default",
            field=models.BooleanField(default=False, verbose_name="По умолчанию"),
        ),
    ]
