# Generated by Django 4.2.17 on 2025-01-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0016_productoption_deleted_at_productoption_deleted_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
    ]
