# Generated by Django 4.2.17 on 2025-01-12 09:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0017_product_is_deleted_productcategory_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="commission",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Комиссия с заказов",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="external_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="Внешний id"),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Старая цена"),
        ),
        migrations.AddField(
            model_name="product",
            name="package_code",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Код упаковки"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=128, null=True, verbose_name="Короткое описание"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="spic_id",
            field=models.CharField(max_length=100, null=True, verbose_name="ИКПУ"),
        ),
        migrations.AddField(
            model_name="product",
            name="vat",
            field=models.IntegerField(
                default=12,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="НДС",
            ),
        ),
    ]
