# Generated by Django 4.2.17 on 2025-01-12 09:53

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0018_product_commission_product_external_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=["name", "description", "short_description"],
                required_languages=(),
                virtual_fields=True,
            ),
        ),
    ]
