# Generated by Django 4.2.17 on 2025-01-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0019_alter_product_i18n"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(default=False, verbose_name="Доступен"),
        ),
    ]
