# Generated by Django 4.2.17 on 2025-01-27 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0020_product_is_available"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="product_images/", verbose_name="Картинка"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(blank=True, null=True, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "активен"), ("inactive", "неактивен")],
                default="active",
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
