# Generated by Django 4.2.17 on 2025-02-04 06:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0021_alter_product_image_alter_product_price_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="commission",
        ),
    ]
