# Generated by Django 4.2.17 on 2025-02-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0022_remove_product_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "активен"), ("inactive", "неактивен")],
                default="inactive",
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
