# Generated by Django 4.2.17 on 2025-02-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0023_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="commission",
            field=models.IntegerField(blank=True, null=True, verbose_name="Комиссия с заказов"),
        ),
    ]
