# Generated by Django 4.2.17 on 2025-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0024_product_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
