# Generated by Django 4.2.17 on 2025-03-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0025_alter_product_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(default=0, verbose_name="Цена"),
        ),
    ]
