# Generated by Django 4.2.17 on 2025-03-20 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0038_institution_legal_name'),
        ('product', '0026_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='institution_branches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_branch_set_product', to='institution.institutionbranch', verbose_name='Филиалы заведений'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='institution_branches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institution_branch_set', to='institution.institutionbranch', verbose_name='Филиалы заведений'),
        ),
    ]
