# Generated by Django 4.2.17 on 2025-03-29 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0039_institutionbranchworker'),
        ('product', '0027_product_institution_branches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='institution_branches',
        ),
        migrations.CreateModel(
            name='ProductToBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('institution_branches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='institution.institutionbranch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='product.product')),
            ],
        ),
    ]
