# Generated by Django 4.2.17 on 2025-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_remove_product_institution_branches_producttobranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
