# Generated by Django 4.2.17 on 2025-05-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_productcategory_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionitem',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productoption',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
