# Generated by Django 4.2.17 on 2025-02-04 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0030_order_self_pickup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Удален")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления"),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[("INCOME", "Приход"), ("OUTCOME", "Расход")],
                        max_length=50,
                        verbose_name="Тип платежа",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cash", "наличными"),
                            ("payme", "payme"),
                            ("terminal", "терминал"),
                        ],
                        max_length=50,
                        verbose_name="Метод оплаты",
                    ),
                ),
                ("amount", models.IntegerField(default=0, verbose_name="Сумма")),
                (
                    "created_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "deleted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Удалил",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
                "ordering": ["-created_at"],
            },
        ),
    ]
