# Generated by Django 4.2.17 on 2025-02-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="receipt_required",
            field=models.BooleanField(default=False, verbose_name="Необходима фискализация"),
        ),
    ]
