# Generated by Django 4.2.17 on 2025-01-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "cash_payment_avaible",
                    models.BooleanField(default=False, verbose_name="Доступна ли наличная оплата"),
                ),
            ],
        ),
    ]
