# Generated by Django 4.2.17 on 2025-02-04 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="common_percentage_ordinary",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов обычный в настройках",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="common_percentage_restaurant_couriers",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов если курьеры самого ресторана в настройках",
            ),
        ),
        migrations.AddField(
            model_name="settings",
            name="common_percentage_self_pickup",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов если самовывоз в настройках",
            ),
        ),
    ]
