# Generated by Django 4.2.17 on 2025-02-05 06:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_settings_common_percentage_ordinary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="settings",
            name="delivery_service_vat_percent",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент НДС услуги по доставке",
            ),
        ),
    ]
