# Generated by Django 4.2.17 on 2025-05-12 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_settings_delivery_service_vat_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='payme_payment_avaible',
            field=models.BooleanField(default=False, verbose_name='Доступна ли оплата через Payme'),
        ),
    ]
