# Generated by Django 4.0.3 on 2022-09-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LastVersions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("android_version", models.CharField(max_length=10)),
                ("ios_version", models.CharField(max_length=10)),
            ],
        ),
    ]
