# Generated by Django 4.2.17 on 2025-01-20 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_lastversions_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lastversions",
            name="android_version",
            field=models.CharField(max_length=10, verbose_name="Версия андроида"),
        ),
        migrations.AlterField(
            model_name="lastversions",
            name="ios_version",
            field=models.CharField(max_length=10, verbose_name="IOS версия"),
        ),
    ]
