# Generated by Django 4.2.17 on 2025-02-05 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OFDReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("terminal_id", models.CharField(max_length=255, verbose_name="ID терминала")),
                ("receipt_seq", models.IntegerField(verbose_name="Номер чека")),
                (
                    "fiscal_sign",
                    models.CharField(max_length=255, verbose_name="Фискальный признак"),
                ),
                ("receipt_date", models.DateTimeField(verbose_name="Дата и время чека")),
                ("qr_code_url", models.CharField(verbose_name="Ссылка на QR-код")),
                (
                    "payment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ofd_receipts",
                        to="payment.payment",
                        verbose_name="Платеж",
                    ),
                ),
            ],
            options={
                "verbose_name": "Чек ОФД",
                "verbose_name_plural": "Чеки ОФД",
                "ordering": ["-receipt_seq"],
            },
        ),
    ]
