# Generated by Django 4.2.17 on 2025-02-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ofd", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ofdreceipt",
            name="fiscal_sign",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Фискальный признак"
            ),
        ),
        migrations.AlterField(
            model_name="ofdreceipt",
            name="qr_code_url",
            field=models.CharField(blank=True, null=True, verbose_name="Ссылка на QR-код"),
        ),
        migrations.AlterField(
            model_name="ofdreceipt",
            name="receipt_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата и время чека"),
        ),
        migrations.AlterField(
            model_name="ofdreceipt",
            name="terminal_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID терминала"
            ),
        ),
    ]
