# Generated by Django 4.2.17 on 2025-02-05 12:27

from django.db import migrations, models
import ofd.models


class Migration(migrations.Migration):
    dependencies = [
        ("ofd", "0002_alter_ofdreceipt_fiscal_sign_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OFDCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "certificate_file",
                    models.FileField(
                        upload_to=ofd.models.get_certificate_upload_to,
                        verbose_name="Файл сертификата",
                    ),
                ),
                ("version", models.IntegerField(blank=True, verbose_name="Версия сертификата")),
                ("expiration_date", models.DateField(verbose_name="Дата истечения")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
                ),
            ],
            options={
                "verbose_name": "Сертификат ОФД",
                "verbose_name_plural": "Сертификаты ОФД",
                "ordering": ["-version", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="ofdreceipt",
            name="is_sent",
            field=models.BooleanField(default=False, verbose_name="Отправлен в офд"),
        ),
        migrations.AlterField(
            model_name="ofdreceipt",
            name="receipt_seq",
            field=models.IntegerField(blank=True, null=True, verbose_name="Номер чека"),
        ),
    ]
