# Generated by Django 4.2.17 on 2025-02-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ofd", "0003_ofdcertificate_ofdreceipt_is_sent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ofdreceipt",
            name="is_sent",
        ),
        migrations.AddField(
            model_name="ofdreceipt",
            name="certificate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receipts",
                to="ofd.ofdcertificate",
                verbose_name="Сертификат",
            ),
        ),
    ]
