# Generated by Django 4.2.17 on 2025-02-07 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ofd", "0004_remove_ofdreceipt_is_sent_ofdreceipt_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="ofdreceipt",
            name="receipt_type",
            field=models.CharField(
                choices=[
                    ("SALE", "Продажа"),
                    ("REFUND", "Возврат"),
                    ("CREDIT", "Кредит"),
                    ("PREPAYMENT", "Аванс"),
                ],
                default="SALE",
                max_length=50,
                verbose_name="Тип чека",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ofdreceipt",
            name="refund_receipt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refunded_receipt",
                to="ofd.ofdreceipt",
                verbose_name="Чек возврата",
            ),
        ),
    ]
