# Generated by Django 4.2.17 on 2025-02-08 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("ofd", "0005_ofdreceipt_receipt_type_ofdreceipt_refund_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="ofdreceipt",
            name="advance_contract_id",
            field=models.UUIDField(
                blank=True,
                default=uuid.uuid4,
                editable=False,
                null=True,
                verbose_name="Идентификатор авансового контракта",
            ),
        ),
    ]
