# Generated by Django 4.2.17 on 2025-01-20 07:12

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "image_stories_ru",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="stories/",
                        validators=[stories.models.validate_mp4_file],
                        verbose_name="Файл сториса русский",
                    ),
                ),
                (
                    "image_stories_uz",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="stories/",
                        validators=[stories.models.validate_mp4_file],
                        verbose_name="Файл сториса узбекский",
                    ),
                ),
                (
                    "image_stories_en",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="stories/",
                        validators=[stories.models.validate_mp4_file],
                        verbose_name="Файл сториса английский",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Время создания"),
                ),
                (
                    "url_link",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Ссылка"),
                ),
            ],
        ),
    ]
