# Generated by Django 4.2.17 on 2025-01-20 12:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stories",
            options={"verbose_name": "История", "verbose_name_plural": "Истории"},
        ),
    ]
