# Generated by Django 4.2.17 on 2025-01-25 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_alter_address_customer_alter_address_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stories", "0002_alter_stories_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="stories",
            name="created_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Создал",
            ),
        ),
        migrations.AddField(
            model_name="stories",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания"),
        ),
        migrations.AddField(
            model_name="stories",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активность"),
        ),
        migrations.AddField(
            model_name="stories",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Номер позиции"),
        ),
        migrations.AddField(
            model_name="stories",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата старта"),
        ),
        migrations.AddField(
            model_name="stories",
            name="title",
            field=models.CharField(max_length=255, null=True, verbose_name="Заголовок"),
        ),
        migrations.AlterField(
            model_name="stories",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.CreateModel(
            name="StoriesToRegion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stories_set",
                        to="address.region",
                        verbose_name="Регион",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="regions",
                        to="stories.stories",
                        verbose_name="Сторис",
                    ),
                ),
            ],
        ),
    ]
