# Generated by Django 4.2.17 on 2025-01-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0003_stories_created_user_stories_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stories",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Заголовок"),
        ),
    ]
