# Generated by Django 4.2.17 on 2025-03-26 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0039_institutionbranchworker"),
        ("stories", "0004_alter_stories_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="stories",
            name="institution",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="institution.institution"
            ),
        ),
    ]
