# Generated by Django 4.2.17 on 2025-04-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0039_institutionbranchworker'),
        ('stories', '0005_stories_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stories',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='institution.institution'),
        ),
    ]
