# Generated by Django 4.2.17 on 2025-07-03 09:25

from django.db import migrations, models
import stories.models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_alter_stories_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='stories',
            name='logo_stories_en',
            field=models.FileField(blank=True, null=True, upload_to='stories/', validators=[stories.models.validate_mp4_file], verbose_name='Лого сториса английский'),
        ),
        migrations.AddField(
            model_name='stories',
            name='logo_stories_ru',
            field=models.FileField(blank=True, null=True, upload_to='stories/', validators=[stories.models.validate_mp4_file], verbose_name='Лого сториса русский'),
        ),
        migrations.AddField(
            model_name='stories',
            name='logo_stories_uz',
            field=models.FileField(blank=True, null=True, upload_to='stories/', validators=[stories.models.validate_mp4_file], verbose_name='Лого сториса узбекский'),
        ),
    ]
