# Generated by Django 4.0.3 on 2022-05-25 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0009_order_address"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymeCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "hidden_number",
                    models.CharField(max_length=16, verbose_name="Спрятанный номер карты"),
                ),
                ("expires", models.CharField(max_length=12, verbose_name="Действует до MMYY")),
                ("token", models.TextField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PaymePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("receipt_id", models.CharField(max_length=255, verbose_name="ID чека")),
                ("total_sum", models.IntegerField(verbose_name="Сумма")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "чек создан"),
                            (1, "создание транзакции"),
                            (2, "списание с карты"),
                            (3, "закрытие транзакции"),
                            (4, "оплачен"),
                            (5, "захолдирован"),
                            (6, "получение команды на холдирование"),
                            (20, "на паузе"),
                            (21, "в очереди на отмену"),
                            (50, "отменен"),
                        ],
                        default=0,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "card",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="payme.paymecard",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="order.order"
                    ),
                ),
            ],
        ),
    ]
