# Generated by Django 4.0.4 on 2022-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payme", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymecard",
            name="name",
            field=models.CharField(default="Card", max_length=255, verbose_name="Название"),
            preserve_default=False,
        ),
    ]
