# Generated by Django 4.2.17 on 2025-01-28 10:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payme", "0002_paymecard_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="paymecard",
            name="hidden_number",
        ),
    ]
