# Generated by Django 4.2.17 on 2025-02-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payme", "0003_remove_paymecard_hidden_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymecard",
            name="hidden_number",
            field=models.CharField(default=12, max_length=20, verbose_name="Номер карты"),
            preserve_default=False,
        ),
    ]
