# Generated by Django 4.2.17 on 2025-05-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0004_paymecard_hidden_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymepayment',
            name='cancel_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='cancel_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='confirm_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='confirm_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='create_receipt_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='create_receipt_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='pay_receipt_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='pay_receipt_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
