# Generated by Django 4.2.17 on 2025-07-09 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0005_paymepayment_cancel_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymecard',
            name='is_verify',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
