# Generated by Django 4.2.17 on 2025-10-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payme', '0006_paymecard_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymepayment',
            name='set_fiscal_data_request',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymepayment',
            name='set_fiscal_data_response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
