# Generated by Django 4.0.3 on 2023-01-05 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0022_alter_orderitem_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PromoCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название")),
                ("description", models.CharField(max_length=256, verbose_name="Описание")),
                ("sum", models.IntegerField(default=15000, verbose_name="Сумма")),
                ("code", models.CharField(max_length=156, verbose_name="Код активации")),
                (
                    "revokable",
                    models.BooleanField(
                        default=False, verbose_name="Деактивировать после использования"
                    ),
                ),
                (
                    "min_order_sum",
                    models.IntegerField(default=30000, verbose_name="Минимальная сумма заказа"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("is_active", models.BooleanField(default=True, verbose_name="Активность")),
                ("start_date", models.DateTimeField(verbose_name="Дата начала")),
                ("end_date", models.DateTimeField(verbose_name="Дата окончания")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromoCodeUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время использования"
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "promo_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="promo_codes.promocode",
                        verbose_name="Промокод",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "ordering": ["-used_at"],
                "unique_together": {("user", "promo_code")},
            },
        ),
    ]
