# Generated by Django 4.0.3 on 2023-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promo_codes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="promocode",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Промокод",
                "verbose_name_plural": "Промокоды",
            },
        ),
        migrations.AlterModelOptions(
            name="promocodeusage",
            options={
                "ordering": ["-used_at"],
                "verbose_name": "Использование промокода",
                "verbose_name_plural": "Использование промокодов",
            },
        ),
        migrations.AlterField(
            model_name="promocode",
            name="code",
            field=models.CharField(max_length=156, unique=True, verbose_name="Код активации"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="description",
            field=models.TextField(blank=True, default="", max_length=512, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="name",
            field=models.CharField(default="Промокод", max_length=64, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="revokable",
            field=models.BooleanField(
                default=False,
                verbose_name="Деактивировать после использования (только для одного пользователя)",
            ),
        ),
    ]
