# Generated by Django 4.2.17 on 2025-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo_codes', '0002_alter_promocode_options_alter_promocodeusage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='status',
            field=models.CharField(default='active', max_length=64, verbose_name='Статус'),
        ),
    ]
