# Generated by Django 4.2.17 on 2025-05-16 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promo_codes', '0003_promocode_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='users',
            field=models.ManyToManyField(related_name='used_promo_codes', to=settings.AUTH_USER_MODEL),
        ),
    ]
