# Generated by Django 4.0.3 on 2022-04-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0004_alter_likedinstitutions_customer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="flat_number",
            field=models.CharField(max_length=255, null=True, verbose_name="Номер квартиры"),
        ),
        migrations.AddField(
            model_name="address",
            name="institution",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
                verbose_name="Заведение",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.CharField(max_length=255, null=True, verbose_name="Широта"),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.CharField(max_length=255, null=True, verbose_name="Долгота"),
        ),
        migrations.AddField(
            model_name="address",
            name="reference_point",
            field=models.CharField(max_length=255, null=True, verbose_name="Ориентир"),
        ),
        migrations.AddField(
            model_name="address",
            name="street",
            field=models.CharField(max_length=255, null=True, verbose_name="Улица"),
        ),
        migrations.AlterField(
            model_name="address",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="address.region",
                verbose_name="Регион",
            ),
        ),
    ]
