# Generated by Django 4.0.2 on 2022-04-19 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0008_institution_end_time_institution_start_time_and_more"),
        ("address", "0002_address_customer_address_flat_number_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="address",
            options={"verbose_name": "Адрес", "verbose_name_plural": "Адреса"},
        ),
        migrations.AlterField(
            model_name="address",
            name="institution",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
                verbose_name="Заведение",
            ),
        ),
    ]
