# Generated by Django 4.0.3 on 2022-05-23 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0009_alter_institution_tags"),
        ("address", "0003_alter_address_options_alter_address_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="name",
            field=models.CharField(default="Default", max_length=255, verbose_name="Название"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="institution",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
                verbose_name="Заведение",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="latitude",
            field=models.CharField(default="39.6525787", max_length=255, verbose_name="Широта"),
        ),
        migrations.AlterField(
            model_name="address",
            name="longitude",
            field=models.CharField(default="66.9568071", max_length=255, verbose_name="Долгота"),
        ),
    ]
