# Generated by Django 4.0.3 on 2022-05-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0004_address_name_alter_address_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="floor",
            field=models.IntegerField(blank=True, null=True, verbose_name="Этаж"),
        ),
        migrations.AlterField(
            model_name="address",
            name="flat_number",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Номер квартиры"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="reference_point",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Ориентир"),
        ),
    ]
