# Generated by Django 4.0.3 on 2022-06-16 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0005_address_floor_alter_address_flat_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
