# Generated by Django 4.0.3 on 2023-01-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_address_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="center",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="center_of_region",
                to="address.address",
                verbose_name="Центр региона",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="radius",
            field=models.FloatField(default=10, verbose_name="Радиус региона"),
        ),
    ]
