# Generated by Django 4.0.3 on 2023-01-05 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0007_region_center_region_radius"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="name",
            field=models.CharField(default="Адрес", max_length=255, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="region",
            name="center",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="center_of_region",
                to="address.address",
                verbose_name="Центр региона",
            ),
        ),
    ]
