# Generated by Django 4.2.17 on 2025-02-05 10:08

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_alter_address_customer_alter_address_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="region",
            name="center",
        ),
        migrations.RemoveField(
            model_name="region",
            name="radius",
        ),
        migrations.AddField(
            model_name="region",
            name="points",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.DecimalField(
                        blank=True, decimal_places=12, max_digits=14, null=True
                    ),
                    size=2,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
