# Generated by Django 4.2.17 on 2025-02-06 08:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0009_remove_region_center_remove_region_radius_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="points",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django.contrib.postgres.fields.ArrayField(
                    base_field=models.DecimalField(
                        blank=True, decimal_places=13, max_digits=15, null=True
                    ),
                    size=2,
                ),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
