# Generated by Django 4.2.17 on 2025-03-16 11:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0010_alter_region_points"),
    ]

    operations = [
        migrations.AddField(
            model_name="region",
            name="polygon",
            field=django.contrib.gis.db.models.fields.PolygonField(
                blank=True, null=True, srid=4326
            ),
        ),
    ]
