# Generated by Django 4.2.17 on 2025-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0011_region_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Текущий адрес'),
        ),
    ]
