# Generated by Django 4.0.3 on 2022-08-26 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("order", "0018_order_fcm_device_alter_order_receipt_id"),
        ("institution", "0019_alter_institution_options_institution_position"),
        ("courier", "0010_courier_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(max_length=255, verbose_name="Значение")),
                ("value", models.PositiveSmallIntegerField(verbose_name="Значение")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="institution.institution",
                        verbose_name="Заведение",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв на заведение",
                "verbose_name_plural": "Отзывы на заведение",
            },
        ),
        migrations.CreateModel(
            name="DeliveryFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("comment", models.CharField(max_length=255, verbose_name="Значение")),
                ("value", models.PositiveSmallIntegerField(verbose_name="Значение")),
                (
                    "courier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courier.courier",
                        verbose_name="Курьер",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв на доставку",
                "verbose_name_plural": "Отзывы на доставку",
            },
        ),
    ]
