# Generated by Django 4.0.3 on 2022-08-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliveryfeedback",
            name="comment",
            field=models.CharField(max_length=255, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="institutionfeedback",
            name="comment",
            field=models.CharField(max_length=255, verbose_name="Комментарий"),
        ),
    ]
