# Generated by Django 4.2.17 on 2025-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_alter_deliveryfeedback_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfeedback',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='institutionfeedback',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Комментарий'),
        ),
    ]
