# Generated by Django 4.2.17 on 2025-04-15 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_alter_deliveryfeedback_comment_and_more'),
        ('feedback', '0003_deliveryfeedback_created_institutionfeedback_created_and_more'),
    ]

    operations = [
    ]
