# Generated by Django 4.2.17 on 2025-04-19 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0039_institutionbranchworker'),
        ('feedback', '0004_merge_20250415_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionfeedback',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_rates', to='institution.institution', verbose_name='Заведение'),
        ),
    ]
