# Generated by Django 4.0.3 on 2022-04-03 08:19

from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название заведения")),
                (
                    "is_open",
                    models.BooleanField(
                        default=False, verbose_name='Открыто ли, по умолчанию "Не открыто"'
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "min_order_sum",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        verbose_name="Минимальная сумма заказа, по умолчанию 0",
                    ),
                ),
                (
                    "delivering_price",
                    models.IntegerField(
                        blank=True, default=6000, verbose_name="Цена доставки, по умолчанию 6000"
                    ),
                ),
                ("phone_number", models.CharField(max_length=255, verbose_name="Номер телефоона")),
                ("tags", models.TextField(verbose_name="Теги")),
                (
                    "type",
                    models.CharField(
                        choices=[("restaurant", "ресторан"), ("shop", "магазин")],
                        max_length=255,
                        verbose_name="Тип заведения",
                    ),
                ),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("description",), required_languages=(), virtual_fields=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Заведение",
                "verbose_name_plural": "Заведения",
            },
        ),
        migrations.CreateModel(
            name="InstitutionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название категории")),
                ("position", models.IntegerField(verbose_name="Позиция в списке")),
                (
                    "i18n",
                    modeltrans.fields.TranslationField(
                        fields=("name",), required_languages=(), virtual_fields=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Категория заведений",
                "verbose_name_plural": "Категории заведений",
                "ordering": ["position"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LikedInstitutions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
            ],
        ),
    ]
