# Generated by Django 4.0.3 on 2022-04-03 08:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="likedinstitutions",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="likedinstitutions",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="institution.institution"
            ),
        ),
        migrations.AddField(
            model_name="institutionrating",
            name="customer",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="institutionrating",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="institution.institution",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="admin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор заведения",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institutioncategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="likedinstitutions",
            unique_together={("customer", "institution")},
        ),
        migrations.AlterUniqueTogether(
            name="institutionrating",
            unique_together={("customer", "institution")},
        ),
    ]
