# Generated by Django 4.0.3 on 2022-04-03 11:06

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutioncategory",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title",), required_languages=(), virtual_fields=True
            ),
        ),
    ]
