# Generated by Django 4.0.3 on 2022-04-07 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0003_alter_institutioncategory_i18n"),
    ]

    operations = [
        migrations.AlterField(
            model_name="likedinstitutions",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="liked_institutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="likedinstitutions",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="likes",
                to="institution.institution",
            ),
        ),
    ]
