# Generated by Django 4.0.3 on 2022-04-09 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0004_alter_likedinstitutions_customer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="owner",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец заведения",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="admin",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор заведения",
            ),
        ),
    ]
