# Generated by Django 4.0.3 on 2022-04-12 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0005_institution_owner_alter_institution_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="admin",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institution_admin",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Администратор заведения",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institution_owner",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец заведения",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="phone_number",
            field=models.CharField(max_length=255, verbose_name="Контактный номер"),
        ),
    ]
