# Generated by Django 4.0.3 on 2022-04-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0006_alter_institution_admin_alter_institution_owner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="image",
            field=models.ImageField(
                null=True, upload_to="institution/images", verbose_name="Картинка"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="logo",
            field=models.ImageField(
                null=True, upload_to="institution/logos/", verbose_name="Логотип"
            ),
        ),
    ]
