# Generated by Django 4.0.2 on 2022-04-19 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0007_institution_image_institution_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="end_time",
            field=models.TimeField(default=datetime.time(22, 0), verbose_name="Время конца работы"),
        ),
        migrations.AddField(
            model_name="institution",
            name="start_time",
            field=models.TimeField(default=datetime.time(9, 0), verbose_name="Время начала работы"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="delivering_price",
            field=models.IntegerField(blank=True, default=6000, verbose_name="Цена доставки"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="is_open",
            field=models.BooleanField(
                default=True, verbose_name='Открыто ли, по умолчанию "открыто"'
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="min_order_sum",
            field=models.IntegerField(
                blank=True, default=0, verbose_name="Минимальная сумма заказа"
            ),
        ),
    ]
