# Generated by Django 4.0.3 on 2022-05-23 11:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0008_institution_end_time_institution_start_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="tags",
            field=models.TextField(blank=True, null=True, verbose_name="Теги"),
        ),
    ]
