# Generated by Django 4.0.3 on 2022-06-01 16:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0009_alter_institution_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="delivering_price",
        ),
        migrations.RemoveField(
            model_name="institution",
            name="min_order_sum",
        ),
        migrations.AddField(
            model_name="institution",
            name="balance",
            field=models.IntegerField(default=0, verbose_name="Баланс заведения"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="institution",
            name="delivery_by_own",
            field=models.BooleanField(default=False, verbose_name="Свои курьеры"),
        ),
        migrations.AddField(
            model_name="institution",
            name="tax_percentage",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="Процент с заказов",
            ),
            preserve_default=False,
        ),
    ]
