# Generated by Django 4.0.4 on 2022-06-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0010_remove_institution_delivering_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="telegram_id_str",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID телеграм, разделенные пробелами",
            ),
        ),
    ]
