# Generated by Django 4.0.3 on 2022-06-04 09:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0011_institution_telegram_id_str"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="tags",
        ),
    ]
