# Generated by Django 4.0.4 on 2022-06-05 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0012_remove_institution_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="max_delivery_time",
            field=models.IntegerField(
                blank=True, default=50, verbose_name="Максимальное время доставки"
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="min_delivery_time",
            field=models.IntegerField(
                blank=True, default=30, verbose_name="Минимальное время доставки"
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="tax_percentage",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов",
            ),
        ),
    ]
