# Generated by Django 4.0.4 on 2022-06-14 07:40

import django.core.validators
from django.db import migrations, models
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0013_institution_max_delivery_time_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institutioncategory",
            old_name="title",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="institution",
            name="balance",
            field=models.IntegerField(blank=True, default=0, verbose_name="Баланс заведения"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="is_open",
            field=models.BooleanField(default=False, verbose_name="Открыто ли"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="tax_percentage",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов",
            ),
        ),
        migrations.AlterField(
            model_name="institutioncategory",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("name",), required_languages=(), virtual_fields=True
            ),
        ),
    ]
