# Generated by Django 4.0.4 on 2022-06-14 09:10

from django.db import migrations
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0014_rename_title_institutioncategory_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="institutioncategory",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="institutioncategory",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=("title",), required_languages=(), virtual_fields=True
            ),
        ),
    ]
