# Generated by Django 4.0.4 on 2022-06-15 09:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0015_rename_name_institutioncategory_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutioncategory",
            name="icon",
            field=models.ImageField(
                null=True, upload_to="categories_icons/", verbose_name="Иконка"
            ),
        ),
    ]
