# Generated by Django 4.0.4 on 2022-06-15 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0016_institutioncategory_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institutioncategory",
            name="icon",
            field=models.FileField(
                null=True, upload_to="categories_icons/", verbose_name="Иконка SVG"
            ),
        ),
    ]
