# Generated by Django 4.0.4 on 2022-07-07 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0017_alter_institutioncategory_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="secondary_categories",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="secondary_institutions",
                to="institution.institutioncategory",
                verbose_name="Вторичные категории",
            ),
        ),
        migrations.AlterField(
            model_name="likedinstitutions",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_institutions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="likedinstitutions",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="institution.institution",
            ),
        ),
    ]
