# Generated by Django 4.0.3 on 2022-08-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0018_institution_secondary_categories_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institution",
            options={
                "ordering": ["position", "id"],
                "verbose_name": "Заведение",
                "verbose_name_plural": "Заведения",
            },
        ),
        migrations.AddField(
            model_name="institution",
            name="position",
            field=models.IntegerField(default=1, verbose_name="Позиция в списке"),
        ),
    ]
