# Generated by Django 4.0.3 on 2022-09-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0019_alter_institution_options_institution_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="free_delivery",
            field=models.BooleanField(default=False),
        ),
    ]
