# Generated by Django 4.0.3 on 2023-01-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0007_region_center_region_radius"),
        ("institution", "0021_alter_institution_secondary_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.region",
            ),
        ),
    ]
