# Generated by Django 4.2.17 on 2025-01-05 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0022_institution_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления"),
        ),
        migrations.AddField(
            model_name="institution",
            name="deleted_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Удалил",
            ),
        ),
        migrations.AddField(
            model_name="institution",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="institution",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
        migrations.AddField(
            model_name="institutioncategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления"),
        ),
        migrations.AddField(
            model_name="institutioncategory",
            name="deleted_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="deleted_%(class)s_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Удалил",
            ),
        ),
        migrations.AddField(
            model_name="institutioncategory",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AddField(
            model_name="institutioncategory",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
    ]
