# Generated by Django 4.2.17 on 2025-01-06 11:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("address", "0008_alter_address_customer_alter_address_name_and_more"),
        ("institution", "0023_institution_deleted_at_institution_deleted_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="Удален")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Дата удаления"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                (
                    "start_time",
                    models.TimeField(
                        default=datetime.time(9, 0), verbose_name="Время начала работы"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        default=datetime.time(22, 0), verbose_name="Время конца работы"
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution_branch",
                        to="address.address",
                        verbose_name="Адрес",
                    ),
                ),
                (
                    "deleted_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deleted_%(class)s_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Удалил",
                    ),
                ),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="institution.institution",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Филиал заведения",
                "verbose_name_plural": "Филиалы заведения",
                "ordering": ["id"],
            },
        ),
    ]
