# Generated by Django 4.2.17 on 2025-01-06 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_alter_address_customer_alter_address_name_and_more"),
        ("institution", "0024_institutionbranch"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionbranch",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institution_branches",
                to="address.region",
                verbose_name="Регион",
            ),
        ),
        migrations.AlterField(
            model_name="institutionbranch",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="institution_branch",
                to="address.address",
                verbose_name="Адрес",
            ),
        ),
    ]
