# Generated by Django 4.2.17 on 2025-01-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0025_institutionbranch_region_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institutionbranch",
            name="region",
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="is_open",
            field=models.BooleanField(default=False, verbose_name="Открыто ли"),
        ),
    ]
