# Generated by Django 4.2.17 on 2025-01-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0026_remove_institutionbranch_region_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionbranch",
            name="telegram_id_str",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID телеграм, разделенные пробелами",
            ),
        ),
    ]
