# Generated by Django 4.2.17 on 2025-01-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0027_institutionbranch_telegram_id_str"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutioncategory",
            name="image",
            field=models.ImageField(
                null=True, upload_to="institution/categories/images/", verbose_name="Фото"
            ),
        ),
    ]
