# Generated by Django 4.2.17 on 2025-01-12 12:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0028_institutioncategory_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="is_available",
            field=models.BooleanField(default=False, verbose_name="Доступен"),
        ),
        migrations.AddField(
            model_name="institution",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="Популярный"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="inn",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="is_available",
            field=models.BooleanField(default=False, verbose_name="Доступен"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="is_pickup_available",
            field=models.BooleanField(default=False, verbose_name="Самовывоз"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="is_telegram_orders_enabled",
            field=models.BooleanField(
                default=False, verbose_name="Принятие заказов через телеграм"
            ),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="legal_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Юридическое название"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="max_preorder_days",
            field=models.IntegerField(
                default=0, verbose_name="Максимальное кол-во дней для предзаказа"
            ),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="min_order_amount",
            field=models.IntegerField(default=0, verbose_name="Минимальная сумма заказа"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="min_preorder_minutes",
            field=models.IntegerField(
                default=0, verbose_name="Минимальное кол-во минут для предзаказа"
            ),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="package_addition_amount",
            field=models.IntegerField(
                default=0, verbose_name="Сумма для добавления пакета в корзину"
            ),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="payme_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Идентификатор Payme"
            ),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="phone_number",
            field=models.CharField(max_length=50, null=True, verbose_name="Номер телефона"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="pinfl",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ПИНФЛ"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="specific_couriers",
            field=models.BooleanField(default=False, verbose_name="Специфичные курьеры"),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="use_auto_dispatcher",
            field=models.BooleanField(default=False, verbose_name="Использовать автодиспетчер"),
        ),
        migrations.CreateModel(
            name="InstitutionBranchSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Понедельник"),
                            ("TUESDAY", "Вторник"),
                            ("WEDNESDAY", "Среда"),
                            ("THURSDAY", "Четверг"),
                            ("FRIDAY", "Пятница"),
                            ("SATURDAY", "Суббота"),
                            ("SUNDAY", "Воскресенье"),
                        ],
                        max_length=30,
                        verbose_name="День недели",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Время начала"),
                ),
                (
                    "end_time",
                    models.TimeField(default=datetime.time(23, 59), verbose_name="Время окончания"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedule_days",
                        to="institution.institutionbranch",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расписание заведения",
                "verbose_name_plural": "Расписания заведения",
                "unique_together": {("day_of_week", "institution")},
            },
        ),
    ]
