# Generated by Django 4.2.17 on 2025-01-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_alter_address_customer_alter_address_name_and_more"),
        ("institution", "0029_institution_is_available_institution_is_popular_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="cash",
            field=models.BooleanField(default=False, verbose_name="Наличная оплата"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="free_delivery",
            field=models.BooleanField(default=False, verbose_name="Бесплатная доставка"),
        ),
        migrations.AlterField(
            model_name="institution",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.region",
                verbose_name="Регион",
            ),
        ),
    ]
