# Generated by Django 4.2.17 on 2025-02-03 11:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0030_institution_cash_alter_institution_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="tax_percentage",
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="tax_percentage_ordinary",
            field=models.IntegerField(
                default=10,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов обычный",
            ),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="tax_percentage_restaurant_couriers",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов если курьеры самого ресторана",
            ),
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="tax_percentage_self_pickup",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов если самовывоз",
            ),
        ),
    ]
