# Generated by Django 4.2.17 on 2025-02-04 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0032_remove_institutionbranch_tax_percentage_ordinary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="tax_percentage_ordinary",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов обычный",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="tax_percentage_restaurant_couriers",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов если курьеры самого ресторана",
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="tax_percentage_self_pickup",
            field=models.IntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MaxValueValidator(100),
                    django.core.validators.MinValueValidator(0),
                ],
                verbose_name="Процент с заказов если самовывоз",
            ),
        ),
    ]
