# Generated by Django 4.2.17 on 2025-02-06 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0009_remove_region_center_remove_region_radius_and_more"),
        ("institution", "0033_alter_institution_tax_percentage_ordinary_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="telegram_id_str",
        ),
        migrations.AddField(
            model_name="institutionbranch",
            name="region_branch",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="institutionbranchs",
                to="address.region",
                verbose_name="Регион работы заведения",
            ),
            preserve_default=False,
        ),
    ]
