# Generated by Django 4.2.17 on 2025-02-11 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0034_remove_institution_telegram_id_str_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="institution",
            name="region",
        ),
    ]
