# Generated by Django 4.2.17 on 2025-02-11 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0035_remove_institution_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="inn",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="ИНН"),
        ),
        migrations.AddField(
            model_name="institution",
            name="pinfl",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="ПИНФЛ"),
        ),
    ]
