# Generated by Django 4.2.17 on 2025-02-17 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0036_institution_inn_institution_pinfl"),
    ]

    operations = [
        migrations.AddField(
            model_name="institutionbranch",
            name="payme",
            field=models.BooleanField(default=False, verbose_name="Payme"),
        ),
    ]
