# Generated by Django 4.2.17 on 2025-03-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0037_institutionbranch_payme"),
    ]

    operations = [
        migrations.AddField(
            model_name="institution",
            name="legal_name",
            field=models.CharField(max_length=255, null=True, verbose_name="Юридическое название"),
        ),
    ]
