# Generated by Django 4.2.17 on 2025-03-25 09:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("institution", "0038_institution_legal_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstitutionBranchWorker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Понедельник"),
                            ("TUESDAY", "Вторник"),
                            ("WEDNESDAY", "Среда"),
                            ("THURSDAY", "Четверг"),
                            ("FRIDAY", "Пятница"),
                            ("SATURDAY", "Суббота"),
                            ("SUNDAY", "Воскресенье"),
                        ],
                        max_length=30,
                        verbose_name="День недели",
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(default=datetime.time(0, 0), verbose_name="Время начала"),
                ),
                (
                    "end_time",
                    models.TimeField(default=datetime.time(23, 59), verbose_name="Время окончания"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активен")),
                (
                    "institution_branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workers",
                        to="institution.institutionbranch",
                        verbose_name="Заведение",
                    ),
                ),
                (
                    "worker",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="worker_branch",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Владелец заведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Работник филиала",
                "verbose_name_plural": "Работники филиала",
                "unique_together": {("worker", "institution_branch")},
            },
        ),
    ]
