# Generated by Django 4.2.17 on 2025-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0039_institutionbranchworker'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='payme',
            field=models.BooleanField(default=False, verbose_name='Оплата через Payme'),
        ),
        migrations.AddField(
            model_name='institutionbranch',
            name='package_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма пакета'),
        ),
    ]
