# Generated by Django 4.2.17 on 2025-05-31 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0040_institution_payme_institutionbranch_package_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Клиент ИД'),
        ),
        migrations.AddField(
            model_name='institution',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Клиент секрет'),
        ),
        migrations.AddField(
            model_name='institutionbranch',
            name='places_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Rkeeper ID'),
        ),
    ]
