# Generated by Django 4.2.17 on 2025-06-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0041_institution_client_id_institution_client_secret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionbranch',
            name='package_spic_id',
            field=models.CharField(max_length=100, null=True, verbose_name='ИКПУ пакета'),
        ),
    ]
