# Generated by Django 4.2.17 on 2025-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0042_institutionbranch_package_spic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionbranch',
            name='package_code',
            field=models.CharField(max_length=100, null=True, verbose_name='Код пакета'),
        ),
    ]
