# Generated by Django 4.2.17 on 2025-06-08 06:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0043_institutionbranch_package_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='institutionbranch',
            name='package_vat',
            field=models.IntegerField(default=12, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='НДС'),
        ),
    ]
