# Generated by Django 4.2.17 on 2025-06-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0012_address_is_current'),
        ('institution', '0044_institutionbranch_package_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutionbranch',
            name='region_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='institutionbranchs', to='address.region', verbose_name='Регион работы заведения'),
        ),
    ]
