# Generated by Django 4.2.17 on 2025-06-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0045_alter_institutionbranch_region_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='is_holding',
            field=models.BooleanField(default=False, verbose_name='Холдирование'),
        ),
    ]
