# Generated by Django 4.2.17 on 2025-07-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0046_institution_is_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='endpoint_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Хост'),
        ),
    ]
