# Generated by Django 4.2.17 on 2025-07-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0047_institution_endpoint_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutioncategory',
            name='position',
            field=models.IntegerField(blank=True, null=True, verbose_name='Позиция в списке'),
        ),
    ]
