# Generated by Django 4.2.17 on 2025-07-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0048_alter_institutioncategory_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='position',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Позиция в списке'),
        ),
    ]
