# Generated by Django 4.0.3 on 2022-05-25 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "min_distance",
                    models.IntegerField(
                        verbose_name="Минимальная дистанция доставки, в километрах"
                    ),
                ),
                (
                    "min_delivery_price",
                    models.IntegerField(verbose_name="Минимальная сумма заказа, в сумах"),
                ),
                ("price_per_km", models.IntegerField(verbose_name="Цена за 1 километр, в сумах")),
            ],
            options={
                "verbose_name": "Настройки доставки",
                "verbose_name_plural": "Настройки доставки",
            },
        ),
        migrations.CreateModel(
            name="Courier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
