# Generated by Django 4.0.3 on 2022-05-31 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courier", "0002_alter_deliverysettings_min_delivery_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
