# Generated by Django 4.0.3 on 2022-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0003_alter_courier_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="passport_series",
            field=models.CharField(
                default="AA111111", max_length=255, verbose_name="Серия паспорта"
            ),
            preserve_default=False,
        ),
    ]
