# Generated by Django 4.0.4 on 2022-06-02 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0011_institution_telegram_id_str"),
        ("courier", "0004_courier_passport_series"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="courier",
            options={"verbose_name": "Курьер", "verbose_name_plural": "Курьеры"},
        ),
    ]
