# Generated by Django 4.0.4 on 2022-06-03 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0011_institution_telegram_id_str"),
        ("courier", "0005_alter_courier_options_alter_deliverysettings_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deliverysettings",
            options={
                "verbose_name": "Глобальные настройки доставки",
                "verbose_name_plural": "Глобальные настройки доставки",
            },
        ),
        migrations.AlterField(
            model_name="deliverysettings",
            name="min_delivery_price",
            field=models.IntegerField(verbose_name="Минимальная сумма доставки, в сумах"),
        ),
        migrations.CreateModel(
            name="InstitutionDeliverySettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "min_distance",
                    models.IntegerField(
                        verbose_name="Минимальная дистанция доставки, в километрах"
                    ),
                ),
                (
                    "min_delivery_price",
                    models.IntegerField(verbose_name="Минимальная сумма доставки, в сумах"),
                ),
                ("price_per_km", models.IntegerField(verbose_name="Цена за 1 километр, в сумах")),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_settings",
                        to="institution.institution",
                        verbose_name="Заведение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки доставки для отдельного заведения",
            },
        ),
    ]
