# Generated by Django 4.0.4 on 2022-06-05 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0006_alter_deliverysettings_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="transport",
            field=models.CharField(
                choices=[("car", "машина"), ("scooter", "скутер"), ("bicycle", "велосипед")],
                default="car",
                max_length=255,
                verbose_name="Вид транспорта",
            ),
            preserve_default=False,
        ),
    ]
