# Generated by Django 4.0.3 on 2022-06-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0007_courier_transport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="transport",
            field=models.CharField(
                choices=[
                    ("car", "машина"),
                    ("scooter", "скутер"),
                    ("bicycle", "велосипед"),
                    ("foot", "пешком"),
                ],
                max_length=255,
                verbose_name="Вид транспорта",
            ),
        ),
    ]
