# Generated by Django 4.0.3 on 2022-06-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0008_alter_courier_transport"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="balance",
            field=models.IntegerField(default=0, verbose_name="Баланс курьера"),
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="Сумма")),
                (
                    "courier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courier.courier",
                        verbose_name="Курьер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
    ]
