# Generated by Django 4.0.3 on 2022-06-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0009_courier_balance_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="status",
            field=models.CharField(
                choices=[
                    ("free", "свободный"),
                    ("delivering", "на доставке"),
                    ("inactive", "неактивный"),
                ],
                default="inactive",
                max_length=255,
                verbose_name="Статус курьера",
            ),
        ),
    ]
