# Generated by Django 4.0.3 on 2023-03-11 17:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0010_courier_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="institutiondeliverysettings",
            options={
                "verbose_name": "Настройки доставки для отдельного заведения",
                "verbose_name_plural": "Настройки доставки для отдельного заведения",
            },
        ),
    ]
