# Generated by Django 4.2.17 on 2024-12-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0011_alter_institutiondeliverysettings_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="Удален"),
        ),
    ]
