# Generated by Django 4.2.17 on 2025-02-18 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("courier", "0012_courier_is_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courier",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courier",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
