# Generated by Django 4.2.17 on 2025-02-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0013_alter_courier_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="courier",
            name="car_info",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Марка машины"
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="registration_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Регистрационный номер машины"
            ),
        ),
        migrations.AddField(
            model_name="courier",
            name="thermal_bag_number",
            field=models.IntegerField(blank=True, null=True, verbose_name="Номер термосумки"),
        ),
    ]
