# Generated by Django 4.2.17 on 2025-05-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0014_courier_car_info_courier_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='status',
            field=models.CharField(choices=[('free', 'свободный'), ('in_institution', 'в заведении'), ('delivering', 'на доставке'), ('inactive', 'неактивный')], default='inactive', max_length=255, verbose_name='Статус курьера'),
        ),
    ]
