# Generated by Django 4.2.17 on 2025-06-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0015_alter_courier_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(blank=True, null=True),
        ),
    ]
