# Generated by Django 4.2.17 on 2025-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courier', '0018_transaction_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='name',
            field=models.CharField(blank=True, null=True),
        ),
    ]
