# Generated by Django 4.0.3 on 2022-04-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("main_admin", "главный администратор системы"),
                    ("admin", "администратор системы"),
                    ("institution_owner", "владелец заведения"),
                    ("institution_admin", "администратор заведения"),
                    ("institution", "заведение"),
                    ("customer", "клиент"),
                ],
                max_length=255,
                null=True,
                verbose_name="Тип пользователя",
            ),
        ),
    ]
