# Generated by Django 4.0.3 on 2022-05-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp",
            field=models.IntegerField(blank=True, null=True, verbose_name="SMS код"),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_expires",
            field=models.DateTimeField(null=True, verbose_name="Срок SMS кода"),
        ),
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("main_admin", "главный администратор системы"),
                    ("admin", "администратор системы"),
                    ("institution_owner", "владелец заведения"),
                    ("institution_admin", "администратор заведения"),
                    ("customer", "клиент"),
                ],
                max_length=255,
                null=True,
                verbose_name="Тип пользователя",
            ),
        ),
    ]
