# Generated by Django 4.0.3 on 2022-06-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0005_user_otp_user_otp_expires_alter_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="otp_change_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="otp_change_number_expires",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
