# Generated by Django 4.0.4 on 2022-07-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0006_user_otp_change_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("main_admin", "главный администратор системы"),
                    ("admin", "администратор системы"),
                    ("institution_owner", "владелец заведения"),
                    ("institution_admin", "администратор заведения"),
                    ("customer", "клиент"),
                    ("operator", "оператор"),
                ],
                max_length=255,
                null=True,
                verbose_name="Тип пользователя",
            ),
        ),
    ]
