# Generated by Django 4.2.17 on 2025-04-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(blank=True, choices=[('main_admin', 'главный администратор системы'), ('admin', 'администратор системы'), ('institution_owner', 'владелец заведения'), ('institution_admin', 'администратор заведения'), ('institution_worker', 'работник заведения'), ('customer', 'клиент'), ('operator', 'оператор'), ('content_manager', 'контент менеджер'), ('logist', 'логист')], max_length=255, null=True, verbose_name='Тип пользователя'),
        ),
    ]
