# Generated by Django 4.2.17 on 2024-12-11 11:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={"verbose_name": "Баннер", "verbose_name_plural": "Баннеры"},
        ),
    ]
