# Generated by Django 4.2.17 on 2025-01-18 11:20

from django.db import migrations, models
import django.db.models.deletion
import modeltrans.fields


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0029_institution_is_available_institution_is_popular_and_more"),
        ("banner", "0002_alter_banner_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="banner",
            name="img",
        ),
        migrations.AddField(
            model_name="banner",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institutioncategory",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="banner",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата окончания"),
        ),
        migrations.AddField(
            model_name="banner",
            name="i18n",
            field=modeltrans.fields.TranslationField(
                fields=["title", "description"], required_languages=(), virtual_fields=True
            ),
        ),
        migrations.AddField(
            model_name="banner",
            name="img_en",
            field=models.ImageField(default="", upload_to="banners/en/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="img_ru",
            field=models.ImageField(default="", upload_to="banners/ru/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="img_uz",
            field=models.ImageField(default="", upload_to="banners/uz/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="banner",
            name="is_active",
            field=models.BooleanField(default=False, verbose_name="Активность"),
        ),
        migrations.AddField(
            model_name="banner",
            name="position",
            field=models.IntegerField(default=0, verbose_name="Номер позиции"),
        ),
        migrations.AddField(
            model_name="banner",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Дата старта"),
        ),
        migrations.AddField(
            model_name="banner",
            name="title",
            field=models.CharField(default="", max_length=255, verbose_name="Заголовок"),
            preserve_default=False,
        ),
    ]
