# Generated by Django 4.2.17 on 2025-02-28 19:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("banner", "0003_remove_banner_img_banner_category_banner_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="banner",
            options={
                "ordering": ("position",),
                "verbose_name": "Баннер",
                "verbose_name_plural": "Баннеры",
            },
        ),
    ]
