# Generated by Django 4.2.17 on 2025-03-08 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0038_institution_legal_name"),
        ("banner", "0004_alter_banner_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="banner",
            name="restaurant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="institution.institution",
                verbose_name="Ресторан",
            ),
        ),
    ]
