# Generated by Django 4.2.17 on 2025-09-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0049_alter_institution_position'),
        ('banner', '0005_banner_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='banner',
            name='restaurants',
            field=models.ManyToManyField(blank=True, related_name='banners', to='institution.institution', verbose_name='Рестораны'),
        ),
    ]
