# Generated by Django 4.0.3 on 2022-04-03 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("institution", "0001_initial"),
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "создан"),
                            ("accepted", "принят"),
                            ("rejected", "отменен"),
                            ("shipped", "в пути"),
                            ("closed", "закрыт"),
                        ],
                        max_length=255,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("note", models.CharField(max_length=300, verbose_name="Комментарий к заказу")),
                ("is_paid", models.BooleanField(default=False, verbose_name="Статус оплаты")),
                ("payment_method", models.CharField(max_length=255, verbose_name="Метод оплаты")),
                ("products_sum", models.IntegerField(verbose_name="Сумма продуктов")),
                ("delivering_sum", models.IntegerField(verbose_name="Сумма доставки")),
                ("total_sum", models.IntegerField(verbose_name="Общая сумма")),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
        migrations.CreateModel(
            name="OrderItemGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("products_sum", models.IntegerField(verbose_name="Сумма продуктов")),
                ("delivering_sum", models.IntegerField(verbose_name="Сумма доставки")),
                ("total_sum", models.IntegerField(verbose_name="Общая сумма")),
                (
                    "institution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="institution.institution",
                        verbose_name="Заведение",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="item_groups",
                        to="order.order",
                        verbose_name="Заказ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("count", models.IntegerField()),
                ("total_sum", models.IntegerField(verbose_name="Сумма")),
                (
                    "options",
                    models.ManyToManyField(to="product.optionitem", verbose_name="Дополнения"),
                ),
                (
                    "order_item_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="order.orderitemgroup",
                        verbose_name="Предмет заказа",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="product.product",
                        verbose_name="Продукт",
                    ),
                ),
            ],
        ),
    ]
