# Generated by Django 4.0.3 on 2022-04-04 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("наличными", "cash"), ("карта", "card"), ("терминал", "terminal")],
                max_length=255,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
