# Generated by Django 4.0.3 on 2022-04-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0003_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivering_sum",
            field=models.IntegerField(default=0, verbose_name="Сумма доставки"),
        ),
        migrations.AlterField(
            model_name="order",
            name="products_sum",
            field=models.IntegerField(default=0, verbose_name="Сумма продуктов"),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_sum",
            field=models.IntegerField(default=0, verbose_name="Общая сумма"),
        ),
        migrations.AlterField(
            model_name="orderitemgroup",
            name="delivering_sum",
            field=models.IntegerField(default=0, verbose_name="Сумма доставки"),
        ),
        migrations.AlterField(
            model_name="orderitemgroup",
            name="products_sum",
            field=models.IntegerField(default=0, verbose_name="Сумма продуктов"),
        ),
        migrations.AlterField(
            model_name="orderitemgroup",
            name="total_sum",
            field=models.IntegerField(default=0, verbose_name="Общая сумма"),
        ),
    ]
