# Generated by Django 4.0.3 on 2022-04-04 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_optionitem_options_alter_productoption_options_and_more"),
        ("order", "0004_alter_order_delivering_sum_alter_order_products_sum_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="options",
        ),
        migrations.CreateModel(
            name="OrderItemToOptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "option_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="product.optionitem",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="order.orderitem",
                    ),
                ),
            ],
        ),
    ]
