# Generated by Django 4.0.3 on 2022-04-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_optionitem_options_alter_productoption_options_and_more"),
        ("order", "0005_remove_orderitem_options_orderitemtooptionitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="options",
            field=models.ManyToManyField(related_name="order_items", to="product.optionitem"),
        ),
        migrations.DeleteModel(
            name="OrderItemToOptionItem",
        ),
    ]
