# Generated by Django 4.0.3 on 2022-04-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0006_orderitem_options_delete_orderitemtooptionitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "наличными"), ("card", "карта"), ("terminal", "терминал")],
                max_length=255,
                verbose_name="Метод оплаты",
            ),
        ),
    ]
