# Generated by Django 4.0.2 on 2022-04-19 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_rename_id_deleted_optionitem_is_deleted"),
        ("order", "0007_alter_order_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="options",
            field=models.ManyToManyField(related_name="order_items", to="product.OptionItem"),
        ),
    ]
