# Generated by Django 4.0.3 on 2022-05-05 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0003_alter_address_options_alter_address_institution"),
        ("order", "0008_alter_orderitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="address.address"
            ),
        ),
    ]
