# Generated by Django 4.0.3 on 2022-05-26 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courier", "0001_initial"),
        ("order", "0009_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courier.courier",
                verbose_name="Курьер",
            ),
        ),
    ]
