# Generated by Django 4.0.4 on 2022-05-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0010_order_courier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создан"),
                    ("accepted", "принят и готовится"),
                    ("rejected", "отменен"),
                    ("ready", "готов"),
                    ("shipped", "в пути"),
                    ("closed", "закрыт"),
                ],
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
