# Generated by Django 4.0.3 on 2022-06-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0011_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="note",
            field=models.CharField(
                blank=True, default="", max_length=300, verbose_name="Комментарий к заказу"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "наличными"), ("payme", "payme"), ("terminal", "терминал")],
                max_length=255,
                verbose_name="Метод оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "создан"),
                    ("pending", "ожидает оплаты"),
                    ("accepted", "принят и готовится"),
                    ("rejected", "отменен"),
                    ("ready", "готов"),
                    ("shipped", "в пути"),
                    ("closed", "закрыт"),
                ],
                max_length=255,
                verbose_name="Статус",
            ),
        ),
    ]
