# Generated by Django 4.0.3 on 2022-06-13 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0012_alter_order_note_alter_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["id"], "verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
    ]
