# Generated by Django 4.0.4 on 2022-06-14 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0013_alter_order_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"], "verbose_name": "Заказ", "verbose_name_plural": "Заказы"},
        ),
    ]
