# Generated by Django 4.0.4 on 2022-07-07 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0010_remove_product_tags"),
        ("institution", "0018_institution_secondary_categories_and_more"),
        ("order", "0014_alter_order_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order_item_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.orderitemgroup",
                verbose_name="Предмет заказа",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="product.product",
                verbose_name="Продукт",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemgroup",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="institution.institution",
                verbose_name="Заведение",
            ),
        ),
        migrations.AlterField(
            model_name="orderitemgroup",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_groups",
                to="order.order",
                verbose_name="Заказ",
            ),
        ),
    ]
