# Generated by Django 4.0.4 on 2022-07-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0016_alter_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt_id",
            field=models.CharField(default="1", max_length=512),
            preserve_default=False,
        ),
    ]
