# Generated by Django 4.0.4 on 2022-08-03 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("fcm_django", "0009_alter_fcmdevice_user"),
        ("order", "0017_order_receipt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fcm_device",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="fcm_django.fcmdevice"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="receipt_id",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
