# Generated by Django 4.0.3 on 2022-08-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0018_order_fcm_device_alter_order_receipt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemgroup",
            name="commission",
            field=models.IntegerField(default=0, verbose_name="Комиссия"),
        ),
    ]
