# Generated by Django 4.0.3 on 2022-09-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0019_orderitemgroup_commission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="receipt_id",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
