# Generated by Django 4.0.3 on 2022-11-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0020_alter_order_receipt_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="preparing_time",
            field=models.IntegerField(blank=True, null=True, verbose_name="Время приготовления"),
        ),
    ]
