# Generated by Django 4.0.3 on 2023-01-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_alter_optionitem_is_default"),
        ("order", "0021_order_preparing_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="options",
            field=models.ManyToManyField(
                blank=True, related_name="order_items", to="product.optionitem"
            ),
        ),
    ]
