# Generated by Django 4.0.3 on 2023-01-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0022_alter_orderitem_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount_sum",
            field=models.IntegerField(default=0, verbose_name="Сумма скидки"),
        ),
    ]
