# Generated by Django 4.0.3 on 2023-03-11 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0015_alter_optionitem_is_default"),
        ("order", "0023_order_discount_sum"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderitem",
            options={"verbose_name": "Продукт заказа", "verbose_name_plural": "Продукты заказа"},
        ),
        migrations.AlterModelOptions(
            name="orderitemgroup",
            options={
                "verbose_name": "Группа продуктов для заказа",
                "verbose_name_plural": "Группы продуктов для заказа",
            },
        ),
        migrations.AlterField(
            model_name="order",
            name="total_sum",
            field=models.IntegerField(default=0, verbose_name="Общая сумма (сумма платежа)"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="count",
            field=models.IntegerField(verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="options",
            field=models.ManyToManyField(
                blank=True,
                related_name="order_items",
                to="product.optionitem",
                verbose_name="Опции",
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order_item_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="order.orderitemgroup",
                verbose_name="Группа",
            ),
        ),
    ]
