# Generated by Django 4.2.17 on 2024-12-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0024_alter_orderitem_options_alter_orderitemgroup_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Завершено"),
        ),
    ]
