# Generated by Django 4.2.17 on 2025-01-09 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("institution", "0027_institutionbranch_telegram_id_str"),
        ("order", "0025_order_completed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitemgroup",
            name="institution_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_item_groups",
                to="institution.institutionbranch",
                verbose_name="Филиал заведения",
            ),
        ),
    ]
