# Generated by Django 4.2.17 on 2025-01-28 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0008_alter_address_customer_alter_address_name_and_more"),
        ("order", "0026_orderitemgroup_institution_branch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="address.address",
                verbose_name="Адресс доставки ?",
            ),
        ),
    ]
