# Generated by Django 4.2.17 on 2025-02-04 05:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0029_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="self_pickup",
            field=models.BooleanField(default=False, verbose_name="Самовывоз заказа"),
        ),
    ]
