# Generated by Django 4.2.17 on 2025-04-25 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0030_order_self_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatusTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparing_start_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало приготовления с')),
                ('preparing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Приготовлено в')),
                ('preparing_lates', models.IntegerField(blank=True, null=True, verbose_name='Принято в')),
                ('courier_assign_at', models.DateTimeField(blank=True, null=True, verbose_name='Назначен курьер с')),
                ('courier_take_it_at', models.DateTimeField(blank=True, null=True, verbose_name='Курьер принял в')),
                ('courier_lates', models.IntegerField(blank=True, null=True, verbose_name='Принято в')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Доставлено в')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='order.order')),
            ],
            options={
                'verbose_name': 'Временные отметки статусов',
                'verbose_name_plural': 'Временные отметки статусов',
            },
        ),
    ]
