# Generated by Django 4.2.17 on 2025-05-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0031_orderstatustimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pre-order', 'пред-заказ'), ('created', 'создан'), ('pending', 'ожидает оплаты'), ('accepted', 'принят'), ('cooking', 'готовится'), ('rejected', 'отменен'), ('ready', 'готов'), ('shipped', 'в пути'), ('closed', 'закрыт')], max_length=255, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='orderstatustimeline',
            name='courier_lates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Задержка доставки'),
        ),
        migrations.AlterField(
            model_name='orderstatustimeline',
            name='preparing_lates',
            field=models.IntegerField(blank=True, null=True, verbose_name='Задержка приготовления'),
        ),
    ]
