# Generated by Django 4.2.17 on 2025-05-09 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0032_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cdt',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
