# Generated by Django 4.2.17 on 2025-05-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0033_order_cdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatustimeline',
            name='courier_arrived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время прибытия курьера'),
        ),
    ]
