# Generated by Django 4.2.17 on 2025-05-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0034_orderstatustimeline_courier_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_amount',
            field=models.IntegerField(default=0, verbose_name='Сумма пакета'),
        ),
    ]
