# Generated by Django 4.2.17 on 2025-06-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0035_order_package_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
