# Generated by Django 4.2.17 on 2025-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0036_order_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_status',
            field=models.CharField(blank=True, choices=[('NEW', 'создан'), ('ACCEPTED_BY_RESTAURANT', 'принят'), ('COOKING', 'готовится'), ('CANCELLED', 'отменен'), ('READY', 'готов')], max_length=60, null=True, verbose_name='Статус Rkeeper'),
        ),
    ]
