# Generated by Django 4.2.17 on 2025-06-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0037_order_restaurant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='package_quantity',
            field=models.IntegerField(default=0, verbose_name='Кол-во пакета'),
        ),
    ]
