# Generated by Django 4.2.17 on 2025-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0038_order_package_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='mid',
            field=models.IntegerField(default=0, verbose_name='ИД Последная сообщения'),
        ),
    ]
