# Generated by Django 4.2.17 on 2025-07-12 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0040_telegrammessage_remove_order_mid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegrammessage',
            name='order_id',
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='order.order'),
            preserve_default=False,
        ),
    ]
