# Generated by Django 4.2.17 on 2025-07-12 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0041_remove_telegrammessage_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrammessage',
            name='message_id2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='message_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='telegrammessage',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
