# Generated by Django 4.2.17 on 2025-07-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0043_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pre-order', 'пред-заказ'), ('created', 'создан'), ('pending', 'ожидает оплаты'), ('accepted', 'принят'), ('cooking', 'готовится'), ('rejected', 'отменен'), ('ready', 'готов'), ('shipped', 'в пути'), ('closed', 'закрыт')], max_length=255, verbose_name='Статус'),
        ),
    ]
