# Generated by Django 4.2.17 on 2025-07-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0044_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_incident',
            field=models.BooleanField(default=False, verbose_name='Инцидентный продукт'),
        ),
    ]
