# Generated by Django 4.2.17 on 2025-07-26 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_optionitem_uuid_product_uuid_productoption_uuid'),
        ('order', '0045_orderitem_is_incident'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='incident_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_items', to='product.product', verbose_name='Инцидентный продукт'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pre-order', 'пред-заказ'), ('created', 'создан'), ('pending', 'ожидает оплаты'), ('accepted', 'принят'), ('cooking', 'готовится'), ('rejected', 'отменен'), ('ready', 'готов'), ('shipped', 'в пути'), ('closed', 'закрыт'), ('incident', 'инцидент')], max_length=255, verbose_name='Статус'),
        ),
    ]
