# Generated by Django 4.2.17 on 2025-07-26 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0046_orderitem_incident_product_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_process',
            field=models.BooleanField(default=False, verbose_name='Обработка заказа'),
        ),
    ]
